### ISSUE TITLE
What's NewBot?

### ISSUE THREAD

**Issue by fengzifz** [cs8425/go-adbbot#2]
`bot := adbbot.NewBot(*DEV, *ADB)`

IDE error: Unresolved reference 'NewBot'

What's the NewBot? I can't find it in this project.

**Comment by cs8425** [comment]
Oops, I forgot to update example. :(
I added a new method `NewRemoteBot()` and rename `NewBot()` to `NewLocalBot()`.
Just replace `NewBot()` to `NewLocalBot()`, and the code should work as usual.
